# Mod BeSlim by Junior_Djjr - MixMods.com.br

[Model]
# Don't change the body model/shape.
# This also removes the need for 3 clumps in the clothes .dff files.
NoFat    = 0
NoMuscle = 0

[Texture]
# Don't change body texture.
# This also removes the need for additional texture in the body .txd files.
# It's currently not possible to disable both, so you will have to choose:
# 1 = Don't get fat.
# 2 = Don't get muscular.
NoFatOrMuscle = 0

[Anim]
# Don't change the animations.
# It will be used the ped.ifp animations instead of the muscular.ifp and fat.ifp.
NoFat    = 1
NoMuscle = 1
