; This file contains the configuration of Switch Driver CLEO mod. 
; If you delete it, rename it or remove any section of it the configuration will return to the default one.

[global]

; The next configuration parameter determines if the mod loads when the game starts.
; The default value it's 0, which means that the mod is enabled. Setting it to 1 will disable the mod.

disablemod=0

; The next configuration parameter determines the mod messages language.
; Write the shortened name of it in uppercase, the variant separated by a "_" (if applicable) and make
; sure you have it installed in order to change the mod language.
; By default it's set to "EN" (Standard English). You can use e.g.: DE, ES and PT.

lang=PT

[cars]

; The next configuration parameter determines if your homie can drive to outside of roads/paths places, like
; in the middle of the desert, beaches, etc.
; However, he'll stop driving on the road/path when he determines he can go there in a straight line,
; but the intelligence used for determine that isn't very well-designed.
; It also allows your homie to reach the marker more precisely if it is on a road/path.
; It's disabled by default due to possibly undesired behaviour. Enable it setting it to 1.

canreachanyplace=0

; The next configuration parameter determines, if your homie'll wander around aimlessly, like a random
; traffic car, or to the target marker.
; Updating the target while this is enabled changes the algorithm seed used to select randomly the path.
; It's disabled by default. Enable it setting it to 1.

wanderaimlessly=0

; The next configuration parameter determines if your homie drives aggressively like you would or not.
; If you want aggressive drive don't change the value. Otherwise set it to 1.

respectfuldriving=0

[helis]

; The next configuration parameter determines the switching to cinematic camera mode on helicopters.
; Default is 0, which means that the camera'll change to cinematic. 1 disables that.

leavecamalone=0

[boats]

; The next configuration parameter enables boats. They don't work very well.
; Activate them at your own risk changing the 0 to a 1.

enabled=0