[Radio Default]
# List:
# 0 = "Playback FM"
# 1 = "K Rose"
# 2 = "K-DST"
# 3 = "Bounce FM"
# 4 = "SF-UR"
# 5 = "Radio Los Santos"
# 6 = "Radio X"
# 7 = "CSR 103.9"
# 8 = "K-JAH West"
# 9 = "Master Sounds 98.3"
# 10 = "WCTR Talk Radio"
# 11 = "User Track Player"
# 12 = "Radio Off
RadioID = 12