; Recarregue todos esses valores in-game digitando "HIND"
[MAIN]
Fonte = 1		    ; Estilo da fonte
Transparencia = 255         ; Transparencia da fonte, 0 até 255, 0 = transparente, 255 = opaco
Largura = 0.3               ; Largura da fonte, aumentar muito causa resultados indesejados
Altura = 1.0                ; Altura da fonte, aumentar muito causa resultados indesejados

Contorno_RED = 0            ; Vermelho do contorno da fonte, 0 até 255
Contorno_GREEN = 0          ; Verde do contorno da donte, 0 até 255
Contorno_BLUE = 0           ; Azul do contorno da fonte, 0 até 255
Contorno_ALPHA = 128        ; Transparencia do contorno, 0 até 255, 0 = transparente, 255 = opaco

Char_Offset = 1.0           ; Altura do texto (vida) em relaçao ao Char, aumente esse valor caso a vida apareça muito abaixo, ou abaixe esse valor caso a vida apareça muito acima