#also see cleo/CustomCrosshairs/profiles/default/profile.ini

#Type "RSCCH" at any time like a cheat to reload all the settings and textures.

[Settings]
#enable loading of crosshair texture from weapon's txd file
#	see readme.txt on how to use this
bAPI = 1

#path relative to cleo/CustomCrosshairs/profiles to load profile.ini and textures from
sProfile = default

#custom folder for profile.ini
#	sProfile is used if commented
; sConfig = 

#custom folder for textures
#	sProfile is used if commented
#uncomment the line below to use a profile with textures having 2x the resolution of default suitable for 1080p
sTextures = default2x
#uncomment the line below to use a profile with textures having 4x the resolution of default suitable for 4K
; sTextures = default4x
#custom path
; sTextures = 

#change crosshair size
#	default 64.0
#	use 0 to disable
#recommended to set to 96.0 if using a profile with textures having resolution higher than default to prevent aliasing
fSize = 0