;==================== Created by Junior_Djjr ====================;   
  
[Front Of You] ;-------------------------------------------------

;---- Limits
DivYuSpeed  = 1.1     ; Divide the car speed to get how many meters will get the car that will divert you - Higher values, closers car you will divert you (you can test better this by enabling "TestMode")
MinSpeed    = 5.0     ; Minimum speed of your and other car should be for deviation

;---- Range
Radius      = 2.8     ; Range to get the car - Higher values, more chances to get the car to divert you, basically the drivers will have more "fear" of you

;---- Light sign
LightSign     = 1     ; Give light sign (1=enable, 0=disable) 
LightMinS     = 11.0  ; Minimum speed for his car to be giving light signal (if you want to let through some high speed (more than 10.0?) To give signal usually on highways etc.)
LightRand     = 25    ; Percentage of chances his car give light signal
LightOnly     = 10    ; Percentage of chances his car only give light signal without diverting from you (when giving light signal)

;---- Divert
MinCurveSide  = 0.5   ; The minimum to the side as his car will turn - very small values ??will make him deviate very little from you
MaxCurveSide  = 1.5   ; Maximum to the side as his car will turn - very large values ??will make him hit the wall alongside
CurveFrnt     = 7.0   ; How to forward his car will turn and stop - Smaller values ??will make it more brake and stop the car over side

;---- Time to divert
MinTime     = 500     ; Minimum time (in milliseconds) to divert and back on the road after divert of you - Less than 500 (half a second), the car probably will not give you time to divert
MaxTime     = 1500    ; Maximum time (in milliseconds) to divert and back on the road after divert of you - More than 1000 (1 second), the car will probably stop and wait a while before returning to driving normally

;---- Tests
TestMode    = 0       ; Test mode shows a luminous ball in front of your car indicating the location that the car should be to divert you (great for testing and setting the value of "DivYuSpeed??")

;====================== MixMods.com.br ========================;