; Damage Screen Blood mod by Junior_Djjr - MixMods.com.br

[Settings]
MaxOpacity = 255   ; 0 até 255. Diminuia para o efeito nunca ficar forte demais.
Increase = 6.0     ; Quanto maior, mais rápido o efeito aumenta.
Decrease = 0.8     ; Quanto maior, mais rápido o efeito diminui.
