[settings]
# "REARLIGHT1" cheat code for edit in game

Red Line Other Players = 0			# 1 - enable, 0 - disable, for SAMP

Copy =5
Intensity Y =0.002
Intensity Z =0.005
Divided Speed =24
Visibility =0.4
Visibility With Nitro =0.4

TailLight =1
TailLight Visibility =50
TailLight Visibility Nitro =100
TailLight Size =1.4
TailLight Size Nitro =1.6

Bike Nitro Red Line = 0			# 1 - enable, 0 - disable

Reverse gear = 1			# 1 - enable, 0 - disable

Nitro white lines effect = 0		# 1 - enable, 0 - disable
Always white lines effect = 0		# 1 - enable, 0 - disable


[Screen Effects]
FOV Nitro = 1				# 1 - enable, 0 - disable
Camera Shake Nitro = 1			# 1 - enable, 0 - disable


[settings_ground]
Enable = 1				# 1 - enable, 0 - disable

# "REARLIGHT2" cheat code for edit in game
Light Size =1.1
Light Size Bike =1.4
Light =40


[settings SAMP]
Intensity Y =0.002
Intensity Z =0.005
Divided Speed =1.0
Visibility =1.0
Visibility With Nitro =0.4