; Simple Free Cam by Junior_Djjr - MixMods.com.br
; If this .ini is not loaded, the mod will work with the default settings

[Keys]
; Numbers: https://www.mixmods.com.br/virtual-keys/
ActivateKey1   = 75    ; First activation key. Default: 73 (K)
ActivateKey2   = 77    ; Second activation key. Press together with the other to enable the mod. Default: 77 (M)

FrontKey       = 73    ; Go forward. Default: 73 (I)
BackKey        = 75    ; Go backwards. Default: 75 (K)

SpeedUpKey     = 48    ; Increase speed (also possible with mouse scroll). You can use -1 to disable. Default: 48 (0)
SpeedDownKey   = 80    ; Decrease speed (ditto). Default: 80 (P)

TeleportKey    = 45    ; Key to teleport CJ to camera position, useful for loading the map. Hold SHIFT to use the ground position. You can use -1 to disable. Default: Insert (45)


[Config]
ShowInfos      = 1     ; Show coordinates and speed on screen. It is re-read on activation.
HideHud        = 0     ; Hide hud and radar/minimap when activating. It is re-read on activation.

InitialSpeed   = 0.1   ; Initial speed.
AddSpeed       = 0.06  ; Increment speed value.

[Save]
SaveKey    = 36    ; Key to save camera position, useful to use in mods etc. You can use -1 to disable. Default: Home (36)
SavedCoords=
SavedPointAt=
