;
; Skid Tweaker by Junior_Djjr - JuniorDjjr.blogspot.com
;

[Sets]
; Tempo em milissegundos da taxa de criação das marcas [padrão é 100]
; Diminuindo irá resultar em curvas mais suaves, mas também aumentará as chances de bater o limite do jogo caso você ficar derrapando muito, e assim, por um tempo, os carros irão parar de soltar as marcas de derrapagem
; Tente balancear isso com o tempo das marcas sumirem, quanto menor o número aqui, mais rapido elas precisarão sumir, ou caso você derrapar demais com algum carro você terá momentos em que as marcas irão parar de ser criadas (até assim algumas sumirem para caber as novas)
Rate    = 75

; Altura das marcas a partir do chão [padrão é 0.1 (10 centímetros)]
; Diminuir demais você poderá ter marcas enfiando no chão e dando efeito z-fighting (piscando), ou aparecer por debaixo das faixas nas ruas etc
Height  = 0.07



[Times]
; FadeStart: Tempo em milissegundos para começar a desaparecer
; FadeEnd: Tempo em milissegundos para terminar de desaparecer
; O limite de tempo é de 65000 (65 segundos), muito cuidado em usar números grandes demais pois o jogo é limitado, ao bater o limite faz as marcas pararem de aparecer até as outras sumirem

; Muito curta
VeryShort_FadeStart = 7500   ; [padrão é 2500]
VeryShort_FadeEnd   = 10000  ; [padrão é 5000]

; Curta
Short_FadeStart     = 15000  ; [padrão é 5000]
Short_FadeEnd       = 20000  ; [padrão é 10000]

; Média
Medium_FadeStart    = 25000  ; [padrão é 10000]
Medium_FadeEnd      = 30000  ; [padrão é 20000]

; Longa
Long_FadeStart      = 25000  ; [padrão é 10000]
Long_FadeEnd        = 30000  ; [padrão é 20000]

; Rastro (terra, areia etc) 
Thread_FadeStart    = 30000  ; [padrão é 10000]
Thread_FadeEnd      = 40000  ; [padrão é 20000]

