[Confg]
LimiteValor = 25000

;Substitua o valor 25000 por outro de sua preferência. Qualquer carro com esse valor ou abaixo dele terá o som de rangido (o valor do carro é definido pelo handling). O carro também precisa ter freios fracos.


Volume = 0.7

;Volume do som.