###### Anim Play by Junior_Djjr - MixMods.com.br ######
# Você pode recarregar este arquivo pressionando R+L+D
#######################################################

[Anim]

# Animation .ifp name.
IFP   = PED

# Animation name.
ANIM  = SEAT_down

# Additional animations if "MODE = 4" or 5. Maximum 2 and must be the same IFP file.
ANIM2 = SEAT_idle
ANIM3 = SEAT_up


KEY  = 51         # Activate key. MixMods.com.br/p/virtual-keys-br.html
JOKERKEY = 164    # Secondary key. Commands will only work if you are holding this key. If you want to activate/deactivate using only one key, set "-1" here.
OFFKEY  = 51      # Key to deactivate. Can be the same as activation.


MODE = 5          # Mode: 0 = without anim; 1 = normal; 2 = forced; 3 = continue walking; 4 = sequence, useful for in-loop-out (in this case, the time settings etc. will only apply to the ANIM2); 5 = Sequence where ANIM2 is running until deactivate.

LOOP = 1          # Put "1" for the animation to repeat.
END  = 0          # Put "1" for the animation to stop in the end pose, that is, when the end of the ped will be in the same position as the end of the animation.
TIME = -1         # Time (in milliseconds) desired for the animation. "-1" makes use of the total time.

WHILE = 0         # Set "1" for, when you release the key, it will force to stop the animation immediately, so the animation will only play while you hold the key.

TALK = 0          # Time (in milliseconds) for the player to move the mouth.


MODEL = -1        # Model ID to appear an object in the body during the animation. Use "-1" to have no object. When using some object, some settings above may not work as expected. This site may be useful: dev.prineside.com/en/gtasa_samp_model_id
BONE = -1         # ID of the bone where the object will be added, for example "6" is right hand. gtamodding.com/wiki/Ped_Bones
X = 0.0           # Bone X coordinate. (can not be rotated)
Y = 0.0           # Bone Y coordinate.
Z = 0.0           # Bone Z coordinate.


# Name the special effect below. Make it empty if you don't want.
EFFECT =

ONTIME = 0        # Delay time for the effect start (in milliseconds).
OFFTIME = 2000    # Time for the effect to be removed.
EX = 0.0          # X coordinate of the player.
EY = 0.0          # Y coordinate of the player.
EZ = 0.0          # Z coordinate of the player.
ERX = 0.0         # X rotation of the player.
ERY = 0.0         # Y rotation of the player.
ERZ = 0.0         # Z rotation of the player.

