; NoClip by Junior_Djjr - MixMods.com.br
; If this .ini doesn't load, the mod will work with the default settings

[Config]
ActiveCommand  = NOC

ShowInfos      = 1     ; Mostrar coordenadas e velocidade na tela

Initial_Speed  = 0.5   ; Velocidade inicial
Add_Speed      = 0.1   ; Velocidade do aumento da velocidade (scroll do mouse)