# Vehicles Test Mod by Junior_Djjr - MixMods.com.br
#
[Settings]
LogLevel = 1  # Use "2" for a bit better detailed log, but the file will be larger.

# Start and end of IDs
IDstart = 400
IDend = 611

# If added vehicles, put the start and end here (if between them there's some ID that doesn't exist or a plane, will crash, so use the "Ignore" bellow).
AddedIDstart = 
AddedIDend = 

# IDs to be ignored (will pass them when testing).
# Change Total and add new lines with ID2, ID3 etc.
[Ignore]
Total = 0
ID1 = 0
