# Ped Fear Fix by Junior_Djjr - MixMods.com.br

[FleeFromGuns]
# Use "0" to completely disable peds running away from you holding a firearm.
Enable = 1

# Minimum radius/distance to activate (int meters)
Radius = 200.0

# Enable it for people run away from you only if you are using a gun (aiming, shooting).
OnlyUsing = 0

# Minimum fear for a ped to be considered a "coward"
# The fear is set in column E of pedstats.dat
MinPedFear = 61

# Application mode
# 1 = 50% of the cowards
# 2 = 100% of the cowards and 50% of noncowards
# 3 = 100% for all
Mode = 2

# Wanted level if some cop see you
# Use "0" to disable
WantedLevel = 1


[FleeFromChainsaw]
# Use "0" to completely disable peds running away from you using a chainsaw (not just holding).
Enable = 1

# Minimum activation radius/distance (in meters)
Radius = 40.0


[FleeFromCarFire]
# Use "0" to completely disable peds running away from cars about to explode.
# It is useful if you use a mod that disables exploding cars.
Enable = 1

# Minimum radius/distance to activate (int meters)
Radius = 30.0
