#also see cleo/CustomCrosshairs/settings.ini

#Type "RSCCH" at any time like a cheat to reload all the settings and textures.

#priority: api > type > parent > animgroup > default > global

#format: ID = path
#	int ID: type/parent/animgroup ID of weapon
#	string path: texture path relative to current textures path

[TypeID]
#see here: http://hotmist.ddo.jp/id/weapon.html

[ParentID]
#see here: https://forum.mixmods.com.br/f294-tutorial/t6212-sa-identifying-added-weapons-through-weapon-highes
22 = pistol
24 = pistol

25 = shotgun
26 = shotgun
27 = shotgun

28 = smg
29 = smg
32 = smg

30 = assault
31 = assault

23 = silenced

37 = flamer

38 = mg

[AnimgroupID]
#see here: http://gtamodding.ru/wiki/%D0%90%D0%B4%D1%80%D0%B5%D1%81%D0%B0_%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%B8_(SA)#WEAPON.DAT
